POST http://localhost:5010/v1.0/invoke/unit-conversion/method/convert HTTP/1.1
content-type: application/json

{
    "value": 56,
    "unitType": "Length",
    "unitStart": "m",
    "unitEnd": "mm"
}

###
POST http://localhost:5010/v1.0/invoke/unit-conversion/method/convert HTTP/1.1
content-type: application/json

{
    "value": 100,
    "unitType": "Temperature",
    "unitStart": "K",
    "unitEnd": "°C"
}

###
POST http://localhost:5010/v1.0/invoke/unit-conversion/method/convert HTTP/1.1
content-type: application/json

{
    "value": 1000,
    "unitType": "Force",
    "unitStart": "N",
    "unitEnd": "kgf"
}